### ISSUE TITLE
Waiting your approval

### ISSUE THREAD

**Issue by HoYoung-City** [herr-biber/dd-pose#17]
Dear DD-Pose Team,

A few months ago, I completed my registration and verified my email for the DD-Pose dataset, as per the instructions provided.
However, I have not yet received your approval and am still eagerly waiting.

Is there anything else I need to do on my end? 
I would greatly appreciate it if you could approve my request.
For your reference, my email is leehoyoung@kw.ac.kr.

Thank you for your time and assistance.

**Comment by herr-biber** [comment]
Hey @HoYoung-City,

Thanks for pinging. I approved your request. Please check and close this GitHub issue if you have access.

--Markus

**Comment by HoYoung-City** [comment]
Thank you for approving my request!
