### ISSUE TITLE
How to access head position coordinates?

### ISSUE THREAD

**Issue by acg93-pixel** [herr-biber/dd-pose#2]
Great work! Just getting started and was wandering; is there a way to get head position coordinates (x-y-z) from the camera's coordinate system?
Using the example in getting_started ipynb I've managed to get only angular representation of head pose.

**Comment by herr-biber** [comment]
Hey @anacej!
The head position (xyz) in the `camdriver` frame can be found in the 4x4 homogeneous transformation matrix you obtain by `di.get_T_camdriver_head(stamp)`:

```
T_camdriver_head = di.get_T_camdriver_head(stamp)
p_head_camdriver = T_camdriver_head[0:3,3]  # first three rows, last column
```

See also https://en.wikipedia.org/wiki/Transformation_matrix#Affine_transformations

**Comment by acg93-pixel** [comment]
Thank you!
