### ISSUE TITLE
Downloading the dataset

### ISSUE THREAD

**Issue by kevinsu628** [herr-biber/dd-pose#3]
Hello, 

I would like to first appreciate you guys for making this work. Compare to the others such as autoPOSE or DriveAHead, your work is the only one that provides a good explanation and a git repo with some starter code. Well done!

I submitted my request for downloading the dataset yesterday. Could you kindly speed up this process by approving it at your end? I'd highly appreciate it. 

Thank you

**Comment by herr-biber** [comment]
Dear Lang Su,

thanks for your interest in the dataset. Good that you escalated the approval. I just approved your request. You should be ready to go. Please shout if you have any more questions.

Bests,
Markus
