### ISSUE TITLE
The zip size is more than 500GB

### ISSUE THREAD

**Issue by kevinsu628** [herr-biber/dd-pose#4]
Hi,

As I am downloading the dataset, I noticed the total size of the zip files seems larger than 500GB. 
Right now the download script is still running, I am already seeing > 700GB in total in my disk. Is there anything I did wrong, or there is an error in counting the size at your end?

Thanks

**Comment by herr-biber** [comment]
The data distribution is as follows:
- `*driver-left-img.tar.gz`: 397 GB
- `*driver-right-img.tar.gz`: 406 GB
- `*metadata.tar.gz`: 21 MB
- `*docu-img.tar.gz`: 83 GB
- `*head-pose.tar.gz`: 27 MB
- **total: 886 GB**

You can remove the files you do not want to download from [resources/download-file-names.txt](https://github.com/herr-biber/dd-pose/blob/master/resources/download-file-names.txt). A minimum setup consists of `*driver-left-img.tar.gz`, `*metadata.tar.gz` and `head-pose.tar.gz`
