### ISSUE TITLE
waiting approval from a DD-Pose administrator

### ISSUE THREAD

**Issue by Phil-Lin** [herr-biber/dd-pose#5]
Hello，I submitted my request for downloading the dataset On February 17th. Could you kindly speed up this process by approving it at your end? I'd highly appreciate it.

Thank you

**Comment by Phil-Lin** [comment]
My application email is phillin702@126.com

**Comment by herr-biber** [comment]
Dear @Phil-Lin,
I wrote you an email with the verification steps to take. Please reopen if you have further issues.

Bests!
