### ISSUE TITLE
Questions about registration

### ISSUE THREAD

**Issue by Yulin-CC** [herr-biber/dd-pose#6]
Hi，I submitted my request for downloading the dataset On March 28th. I will appreciate it if you kindly speed up this process to approving my registration. Looking forward to your apply.

My registration mailbox is 1595928039@qq.com.

Best regard.

**Comment by herr-biber** [comment]
Hi @Rolin-C . Thanks for reaching out. Please check your inbox with respect to providing your proof of affiliation. I'll happily approve the account afterwards. Feel free to ping me in case you need further assistance.

Bests,
Markus
